<div id="main-page-content">

  <?php 
    require 'overlays/add-clipping.php';
    require 'overlays/share.php';
    require 'overlays/add-notebook.php';
    $fname = $_SESSION['fname'];
  ?>

	<div id="content-header">
		<div id="clipping-title">
			
		</div>
    <div id="info-button">
      info
    </div>
		<div id="share-button" onclick="showShareOverlay()">
			Share
		</div>
		<div id="organize-button">
			Organize
		</div>
	</div>

  <textarea id="clipping-content">
  </textarea>

  <div id="comments-area">
    <div id="comments-header">
      <h3 id="comments-header-text">Comments</h3>
      <!-- <div id="comments-header-horizontal-line"></div> -->
    </div>
    <div id="new-comment-row">
      <form id="comment-form" action="" enctype="multipart/form-data" method="POST">
        <textarea type="text" id="comment-content" name="comment-content" placeholder="Enter a comment..." onkeyup="addCommentIsReady()" onchange="addCommentIsReady()" required></textarea>
        <button type="submit" id="comment-submit">Comment</button>
      </form>
    </div>
    <div id="comments-content">
      <!-- Populated with comments generated by api/markup/markup-comment_row.php -->
    </div>
  </div>

  <div id="new-user-area">
    <h1>Welcome <?PHP echo $fname ?>!</h1>
    <h3>Let's start by creating a clipping. Watch how to create a clipping below.</h3>
    <video autoplay loop>
      <source src="http://<?php echo $_SERVER['HTTP_HOST'] . $_IWP_DIR_;?>/assets/video/vid_2.mp4" type="video/mp4"/>
    </video>
  </div>
</div>

<script>

document.querySelector('#info-button').onclick = function(){
	swal("Feature not implemented", "We'll get that working right away!")
};

document.querySelector('#organize-button').onclick = function(){
	swal("Feature not implemented", "We'll get that working right away!")
};

</script>

